# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_robochair', [dirname(__file__)])
        except ImportError:
            import _robochair
            return _robochair
        if fp is not None:
            try:
                _mod = imp.load_module('_robochair', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _robochair = swig_import_helper()
    del swig_import_helper
else:
    import _robochair
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def ReplaceString(*args):
  return _robochair.ReplaceString(*args)
ReplaceString = _robochair.ReplaceString

def sleepms(*args):
  return _robochair.sleepms(*args)
sleepms = _robochair.sleepms
class RoboteqDevice(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RoboteqDevice, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RoboteqDevice, name)
    __repr__ = _swig_repr
    def IsConnected(self): return _robochair.RoboteqDevice_IsConnected(self)
    def Connect(self, *args): return _robochair.RoboteqDevice_Connect(self, *args)
    def Disconnect(self): return _robochair.RoboteqDevice_Disconnect(self)
    def SetConfig(self, *args): return _robochair.RoboteqDevice_SetConfig(self, *args)
    def SetCommand(self, *args): return _robochair.RoboteqDevice_SetCommand(self, *args)
    def GetConfig(self, *args): return _robochair.RoboteqDevice_GetConfig(self, *args)
    def GetName(self): return _robochair.RoboteqDevice_GetName(self)
    def GetValue(self, *args): return _robochair.RoboteqDevice_GetValue(self, *args)
    def __init__(self): 
        this = _robochair.new_RoboteqDevice()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _robochair.delete_RoboteqDevice
    __del__ = lambda self : None;
RoboteqDevice_swigregister = _robochair.RoboteqDevice_swigregister
RoboteqDevice_swigregister(RoboteqDevice)

_GO = _robochair._GO
_MOTCMD = _robochair._MOTCMD
_MOTPOS = _robochair._MOTPOS
_MOTVEL = _robochair._MOTVEL
_SENCNTR = _robochair._SENCNTR
_SBLCNTR = _robochair._SBLCNTR
_VAR = _robochair._VAR
_ACCEL = _robochair._ACCEL
_DECEL = _robochair._DECEL
_DOUT = _robochair._DOUT
_DSET = _robochair._DSET
_DRES = _robochair._DRES
_HOME = _robochair._HOME
_ESTOP = _robochair._ESTOP
_MGO = _robochair._MGO
_G = _robochair._G
_M = _robochair._M
_P = _robochair._P
_S = _robochair._S
_C = _robochair._C
_CB = _robochair._CB
_AC = _robochair._AC
_DC = _robochair._DC
_DS = _robochair._DS
_D1 = _robochair._D1
_D0 = _robochair._D0
_H = _robochair._H
_EX = _robochair._EX
_MG = _robochair._MG
_MOTAMPS = _robochair._MOTAMPS
_MOTPWR = _robochair._MOTPWR
_ABSPEED = _robochair._ABSPEED
_ABCNTR = _robochair._ABCNTR
_BLCNTR = _robochair._BLCNTR
_RELSPEED = _robochair._RELSPEED
_RELCNTR = _robochair._RELCNTR
_BLRCNTR = _robochair._BLRCNTR
_BLSPEED = _robochair._BLSPEED
_BLRSPEED = _robochair._BLRSPEED
_BATAMPS = _robochair._BATAMPS
_VOLTS = _robochair._VOLTS
_DIGIN = _robochair._DIGIN
_DIN = _robochair._DIN
_ANAIN = _robochair._ANAIN
_PLSIN = _robochair._PLSIN
_TEMP = _robochair._TEMP
_FEEDBK = _robochair._FEEDBK
_STFLAG = _robochair._STFLAG
_FLTFLAG = _robochair._FLTFLAG
_DIGOUT = _robochair._DIGOUT
_LPERR = _robochair._LPERR
_CMDSER = _robochair._CMDSER
_CMDANA = _robochair._CMDANA
_CMDPLS = _robochair._CMDPLS
_TIME = _robochair._TIME
_LOCKED = _robochair._LOCKED
_A = _robochair._A
_SR = _robochair._SR
_CR = _robochair._CR
_CBR = _robochair._CBR
_BS = _robochair._BS
_BSR = _robochair._BSR
_BA = _robochair._BA
_V = _robochair._V
_D = _robochair._D
_DI = _robochair._DI
_AI = _robochair._AI
_PI = _robochair._PI
_T = _robochair._T
_F = _robochair._F
_FS = _robochair._FS
_FF = _robochair._FF
_DO = _robochair._DO
_E = _robochair._E
_CIS = _robochair._CIS
_CIA = _robochair._CIA
_CIP = _robochair._CIP
_TM = _robochair._TM
_LK = _robochair._LK
_CAD = _robochair._CAD
_OVL = _robochair._OVL
_UVL = _robochair._UVL
_THLD = _robochair._THLD
_MXMD = _robochair._MXMD
_PWMF = _robochair._PWMF
_CPRI = _robochair._CPRI
_RWD = _robochair._RWD
_ECHOF = _robochair._ECHOF
_PMS = _robochair._PMS
_ACS = _robochair._ACS
_AMS = _robochair._AMS
_CLIN = _robochair._CLIN
_DFC = _robochair._DFC
_DINA = _robochair._DINA
_DINL = _robochair._DINL
_DOA = _robochair._DOA
_DOL = _robochair._DOL
_AMOD = _robochair._AMOD
_AMIN = _robochair._AMIN
_AMAX = _robochair._AMAX
_ACTR = _robochair._ACTR
_ADB = _robochair._ADB
_ALIN = _robochair._ALIN
_AINA = _robochair._AINA
_AMINA = _robochair._AMINA
_AMAXA = _robochair._AMAXA
_APOL = _robochair._APOL
_PMOD = _robochair._PMOD
_PMIN = _robochair._PMIN
_PMAX = _robochair._PMAX
_PCTR = _robochair._PCTR
_PDB = _robochair._PDB
_PLIN = _robochair._PLIN
_PINA = _robochair._PINA
_PMINA = _robochair._PMINA
_PMAXA = _robochair._PMAXA
_PPOL = _robochair._PPOL
_MMOD = _robochair._MMOD
_MXPF = _robochair._MXPF
_MXPR = _robochair._MXPR
_ALIM = _robochair._ALIM
_ATRIG = _robochair._ATRIG
_ATGA = _robochair._ATGA
_ATGD = _robochair._ATGD
_KP = _robochair._KP
_KI = _robochair._KI
_KD = _robochair._KD
_PIDM = _robochair._PIDM
_ICAP = _robochair._ICAP
_MAC = _robochair._MAC
_MDEC = _robochair._MDEC
_MVEL = _robochair._MVEL
_MXRPM = _robochair._MXRPM
_MXTRN = _robochair._MXTRN
_CLERD = _robochair._CLERD
_BPOL = _robochair._BPOL
_BLSTD = _robochair._BLSTD
_BLFB = _robochair._BLFB
_BHOME = _robochair._BHOME
_BLL = _robochair._BLL
_BHL = _robochair._BHL
_BLLA = _robochair._BLLA
_BHLA = _robochair._BHLA
_SXC = _robochair._SXC
_SXM = _robochair._SXM
_EMOD = _robochair._EMOD
_EPPR = _robochair._EPPR
_ELL = _robochair._ELL
_EHL = _robochair._EHL
_ELLA = _robochair._ELLA
_EHLA = _robochair._EHLA
_KPC1 = _robochair._KPC1
_KPC2 = _robochair._KPC2
_KIC1 = _robochair._KIC1
_KIC2 = _robochair._KIC2
_KDC1 = _robochair._KDC1
_KDC2 = _robochair._KDC2
_EHOME = _robochair._EHOME
RQ_INVALID_HANDLE = _robochair.RQ_INVALID_HANDLE
RQ_SUCCESS = _robochair.RQ_SUCCESS
RQ_ERR_OPEN_PORT = _robochair.RQ_ERR_OPEN_PORT
RQ_ERR_NOT_CONNECTED = _robochair.RQ_ERR_NOT_CONNECTED
RQ_ERR_TRANSMIT_FAILED = _robochair.RQ_ERR_TRANSMIT_FAILED
RQ_ERR_SERIAL_IO = _robochair.RQ_ERR_SERIAL_IO
RQ_ERR_SERIAL_RECEIVE = _robochair.RQ_ERR_SERIAL_RECEIVE
RQ_INVALID_RESPONSE = _robochair.RQ_INVALID_RESPONSE
RQ_UNRECOGNIZED_DEVICE = _robochair.RQ_UNRECOGNIZED_DEVICE
RQ_UNRECOGNIZED_VERSION = _robochair.RQ_UNRECOGNIZED_VERSION
RQ_INVALID_CONFIG_ITEM = _robochair.RQ_INVALID_CONFIG_ITEM
RQ_INVALID_OPER_ITEM = _robochair.RQ_INVALID_OPER_ITEM
RQ_INVALID_COMMAND_ITEM = _robochair.RQ_INVALID_COMMAND_ITEM
RQ_INDEX_OUT_RANGE = _robochair.RQ_INDEX_OUT_RANGE
RQ_SET_CONFIG_FAILED = _robochair.RQ_SET_CONFIG_FAILED
RQ_GET_CONFIG_FAILED = _robochair.RQ_GET_CONFIG_FAILED
RQ_GET_VALUE_FAILED = _robochair.RQ_GET_VALUE_FAILED
RQ_SET_COMMAND_FAILED = _robochair.RQ_SET_COMMAND_FAILED
# This file is compatible with both classic and new-style classes.


